# Build gqlc in a stock Go builder container
FROM golang:1.14.2-alpine as builder

ARG BUILD_ACT=build

RUN apk add --no-cache make gcc musl-dev linux-headers git

COPY . /qlcchain/qlc-pool

RUN \
    cd /qlcchain/qlc-pool && go mod download && rm -rf /qlcchain
